import {
  addDoc,
  arrayRemove,
  arrayUnion,
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  getFirestore,
  query,
  setDoc,
  where,
} from 'firebase/firestore';

import firebase_app from '@/firebase/config';

const db = getFirestore(firebase_app);

export async function appendFileDataToUser(
  userId: string,
  filesData: Map<string, string>[]
) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userId);

  // TODO: Fix this when I fix firebase realtime update, this should be one api call not many
  for (const data of filesData) {
    const value = {
      files: arrayUnion({
        fileName: data['fileName'],
        openAiFileId: data['openAiFileId'],
      }),
    };

    try {
      await setDoc(docRef, value, { merge: true });
    } catch (e) {
      console.log(e);
    }
  }
}

export async function appendDocumentSpecificFileIds(
  documentId: string,
  files: Map<string, string>[]
) {
  const result: any[] = [];
  const error: Error[] = [];
  const documentsRef = collection(db, 'documents');
  const docRef = doc(documentsRef, documentId);

  for (const file of files) {
    const value = {
      files: arrayUnion({
        fileName: file['fileName'],
        openAiFileId: file['openAiFileId'],
      }),
    };

    try {
      result.push(await setDoc(docRef, value, { merge: true }));
    } catch (e) {
      error.push(e);
    }
  }

  return { error, result };
}

// TODO: refactor below 4 methods into a single method which accepts different params
export async function getUserUploadedFilesData(userid: string) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userid);
  let result;
  let error;

  try {
    result = await getDoc(docRef).then((data) => data.get('files'));
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function getUserInfo(userid: string) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userid);

  const result = await getDoc(docRef);
  const savedAssistantId = result.get('assistantId');
  const savedVectorStoreId = result.get('vectorStoreId');
  const savedOpenAiChatAssistantId = result.get('openAiChatAssistantId');
  const savedActiveDocumentName = result.get('activeDocumentName');
  return {
    savedActiveDocumentName,
    savedAssistantId,
    savedOpenAiChatAssistantId,
    savedVectorStoreId,
  };
}

export async function getUserOwnedDocuments(userId: string) {
  return await getDocs(
    query(collection(db, 'documents'), where('documentOwnerId', '==', userId))
  );
}

export async function updateDocumentTitle(documentId: string, documentName: string) {
  const documentsRef = collection(db, "documents");
  let error, result;
  try {
    result = await setDoc(doc(documentsRef, documentId), { documentName }, { merge: true })
  } catch (e) {
    error = e;
  }

  return { error, result }
}

export async function saveCurrentDocumentState(
  userId: string,
  documentName: string,
  threadId: string,
  documentVectorStoreId: string,
  document: any,
  documentId?: string
) {
  const documentsRef = collection(db, 'documents');
  let error, result;
  try {
    const value = {
      document: document,
      documentName: documentName,
      documentOwnerId: userId,
      threadId: threadId,
      vectorStoreId: documentVectorStoreId,
    };

    result = documentId
      ? await setDoc(doc(documentsRef, documentId), value, { merge: true })
      : await addDoc(documentsRef, value);
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function saveUserTemplate(
  userId: string,
  templateName: string,
  template: any,
  isTemplateOwner: boolean,
  templateId?: string
) {
  const templatesRef = collection(db, "templates");
  let docId, error, result;

  try {
    const value = {
      template,
      templateName,
      templateOwnerId: userId,
    };

    if (templateId && isTemplateOwner) {
      await setDoc(doc(templatesRef, templateId), value, { merge: true });
      docId = templateId; // Since we're updating an existing document, return the provided ID
    } else {
      const docRef = await addDoc(templatesRef, value);
      docId = docRef.id; // Get the autogenerated Firestore ID
      result = docRef;
    }
  } catch (e) {
    error = e;
  }

  return { docId, error, result };
}

export async function saveUserActiveAssistant(
  userId: string,
  assistantId: string,
  vectoreStoreId: string,
  openAiChatAssistantId: string
) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userId);

  const result = await setDoc(
    docRef,
    {
      assistantId: assistantId,
      openAiChatAssistantId: openAiChatAssistantId,
      vectorStoreId: vectoreStoreId,
    },
    { merge: true }
  );

  return { result };
}

export async function getOwnedTemplates(templateOwnerId: string) {
  return await getDocs(
    query(
      collection(db, 'templates'),
      where('templateOwnerId', '==', templateOwnerId)
    )
  );
}

export async function deleteTemplate(templateId: string) {
  const documentsRef = collection(db, 'templates');
  const docRef = doc(documentsRef, templateId);
  let error, result;

  try {
    result = await deleteDoc(docRef);
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function deleteDocument(documentId: string) {
  const documentsRef = collection(db, 'documents');
  const docRef = doc(documentsRef, documentId);
  let error, result;

  try {
    result = await deleteDoc(docRef);
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function deleteUserUploadedFile(
  userId: string,
  fileName: string,
  openAiFileId: string
) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userId);
  let error, result;

  const value = {
    files: arrayRemove({
      fileName: fileName,
      openAiFileId: openAiFileId,
    }),
  };

  try {
    result = await setDoc(docRef, value, { merge: true });
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function getAssistants(assistantOwnerId: string) {
  return await getDocs(
    query(
      collection(db, 'assistants'),
      where('ownerId', '==', assistantOwnerId)
    )
  );
}
