import {
  addDoc,
  arrayRemove,
  arrayUnion,
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  getFirestore,
  onSnapshot,
  query,
  setDoc,
  where,
} from 'firebase/firestore';

import firebase_app from '@/firebase/config';
import { SlackIntegration, TokenNodeUsage, UserIntegrations } from '@/types';

const db = getFirestore(firebase_app);

export async function appendFileDataToUser(
  userId: string,
  filesData: { fileIds: string[]; fileName: string; status: string }[]
) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userId);

  const value = {
    files: arrayUnion(...filesData.map(file => ({
      fileIds: file.fileIds,
      fileName: file.fileName
    })))
  };

  try {
    await setDoc(docRef, value, { merge: true });
  } catch (e) {
    console.error('Error appending file data:', e);
    throw e;
  }
}

export async function appendChatSpecificFileIds(
  chatId: string,
  files: { fileIds: string[]; fileName: string; status: string }[]
) {
  const result: any[] = [];
  const error: Error[] = [];
  const chatsRef = collection(db, 'chats');
  const chatRef = doc(chatsRef, chatId);

  const value = {
    files: arrayUnion(...files.map(file => ({
      fileIds: file.fileIds,
      fileName: file.fileName
    })))
  };

  try {
    result.push(await setDoc(chatRef, value, { merge: true }));
  } catch (e) {
    error.push(e);
  }

  return { error, result };
}

// TODO: refactor below 4 methods into a single method which accepts different params
export async function getUserUploadedFilesData(userid: string) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userid);
  let result;
  let error;

  try {
    result = await getDoc(docRef).then((data) => data.get('files'));
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function getUserOwnedDocuments(userId: string) {
  return await getDocs(
    query(collection(db, 'documents'), where('documentOwnerId', '==', userId))
  );
}

export async function updateDocumentTitle(documentId: string, documentName: string) {
  const documentsRef = collection(db, "documents");
  let error, result;
  try {
    result = await setDoc(doc(documentsRef, documentId), { documentName }, { merge: true })
  } catch (e) {
    error = e;
  }

  return { error, result }
}

export async function saveCurrentDocumentState(
  userId: string,
  documentName: string,
  chatId: string,
  document: any,
  documentId?: string
) {
  const documentsRef = collection(db, 'documents');
  let error, result;
  try {
    const value = {
      chatId: chatId,
      document: document,
      documentName: documentName,
      documentOwnerId: userId,
    };

    result = documentId
      ? await setDoc(doc(documentsRef, documentId), value, { merge: true })
      : await addDoc(documentsRef, value);
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function saveUserTemplate(
  userId: string,
  templateName: string,
  template: any,
  isTemplateOwner: boolean,
  templateId?: string
) {
  const templatesRef = collection(db, "templates");
  let docId, error, result;

  try {
    const value = {
      template,
      templateName,
      templateOwnerId: userId,
    };

    if (templateId && isTemplateOwner) {
      await setDoc(doc(templatesRef, templateId), value, { merge: true });
      docId = templateId; // Since we're updating an existing document, return the provided ID
    } else {
      const docRef = await addDoc(templatesRef, value);
      docId = docRef.id; // Get the autogenerated Firestore ID
      result = docRef;
    }
  } catch (e) {
    error = e;
  }

  return { docId, error, result };
}

export async function getOwnedTemplates(templateOwnerId: string) {
  return await getDocs(
    query(
      collection(db, 'templates'),
      where('templateOwnerId', '==', templateOwnerId)
    )
  );
}

export async function deleteTemplate(templateId: string) {
  const documentsRef = collection(db, 'templates');
  const docRef = doc(documentsRef, templateId);
  let error, result;

  try {
    result = await deleteDoc(docRef);
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function deleteDocument(documentId: string) {
  const documentsRef = collection(db, 'documents');
  const docRef = doc(documentsRef, documentId);
  let error, result;

  try {
    result = await deleteDoc(docRef);
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function deleteUserUploadedFile(
  userId: string,
  fileName: string,
  fileIds: string[]
) {
  const usersRef = collection(db, 'users');
  const docRef = doc(usersRef, userId);
  let error, result;

  const value = {
    files: arrayRemove({
      fileIds: fileIds,
      fileName: fileName
    }),
  };

  try {
    result = await setDoc(docRef, value, { merge: true });
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function createNewChat(userId: string, documentId: string, chatId: string) {
  const chatsRef = collection(db, 'chats');
  let error, result;

  try {
    const value = {
      chatName: 'Untitled',
      documentIds: [documentId],
      messages: [],
      userId: userId
    };

    await setDoc(doc(chatsRef, chatId), value);
    result = { id: chatId };
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function getUserChats(userId: string) {
  const chatsRef = collection(db, 'chats');
  let error, result;

  try {
    const querySnapshot = await getDocs(
      query(chatsRef, where('userId', '==', userId))
    );
    result = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }));
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function storeMessage(chatId: string, message: {
  id: number,
  content: string,
  role: "assistant" | "user",
  fileNames?: string[],
  reasoning?: string
}) {
  const chatsRef = collection(db, 'chats');
  const docRef = doc(chatsRef, chatId);
  let error, result;

  try {
    result = await setDoc(docRef, {
      messages: arrayUnion(message)
    }, { merge: true });
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function getChatMessages(chatId: string) {
  const chatsRef = collection(db, 'chats');
  const docRef = doc(chatsRef, chatId);
  let error, result;

  try {
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      result = docSnap.data().messages || [];
    } else {
      result = [];
    }
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function deleteChat(chatId: string) {
  const chatsRef = collection(db, 'chats');
  const docRef = doc(chatsRef, chatId);
  let error, result;

  try {
    result = await deleteDoc(docRef);
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function getDocumentById(documentId: string) {
  const documentsRef = collection(db, 'documents');
  const docRef = doc(documentsRef, documentId);
  let error, result;

  try {
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      result = { id: docSnap.id, ...docSnap.data() };
    }
  } catch (e) {
    error = e;
  }

  return { error, result };
}

export async function updateUserLastLoginTimestamp(userId: string) {
  const usersRef = collection(db, 'users');
  const userDocRef = doc(usersRef, userId);
  const now = new Date().toISOString().replace(/\.\d+Z$/, 'Z');

  try {
    await setDoc(userDocRef, { lastLoginTimestamp: now }, { merge: true });
    return { success: true };
  } catch (error) {
    console.error('Error updating Firestore timestamp:', error);
    return { error, success: false };
  }
}

// New function to get user's integrations data
export async function getUserIntegrations(userId: string): Promise<{ integrations: UserIntegrations | null, error?: any }> {
  const userDocRef = doc(db, 'users', userId);
  let frontendIntegrations: UserIntegrations | null = null;
  try {
    const docSnap = await getDoc(userDocRef);
    if (docSnap.exists()) {
      const data = docSnap.data();
      const backendIntegrations = data?.integrations;
      // Extract only the status information for the frontend
      if (backendIntegrations?.slack) {
        const slackData: SlackIntegration = backendIntegrations.slack;
        frontendIntegrations = { slack: { expiresAt: slackData.expiresAt ?? null, integrated: true } };
      }
      return { integrations: frontendIntegrations };
    } else {
      return { integrations: null };
    }
  } catch (error) {
    console.error('Error fetching user integrations:', error);
    return { error, integrations: null };
  }
}

// New function for real-time token usage updates
export function subscribeToChatTokenUsage(
  chatId: string,
  callback: (tokensUsed: TokenNodeUsage[] | undefined) => void
): () => void { // Returns an unsubscribe function
  if (!chatId) {
    console.error("subscribeToChatTokenUsage requires a chatId.");
    return () => {}; // Return a no-op unsubscribe function
  }

  const chatDocRef = doc(db, 'chats', chatId);

  const unsubscribe = onSnapshot(
    chatDocRef,
    (docSnap) => {
      if (docSnap.exists()) {
        const data = docSnap.data();
        // Pass the tokensUsed array (or undefined if not present) to the callback
        callback(data?.tokensUsed as TokenNodeUsage[] | undefined);
      } else {
        console.warn(`Chat document ${chatId} not found for token subscription.`);
        callback(undefined); // Indicate data is not available
      }
    },
    (error) => {
      console.error(`Error listening to chat ${chatId} for token usage:`, error);
      // Optionally call callback with an error state or specific value
      callback(undefined);
    }
  );

  // Return the unsubscribe function provided by onSnapshot
  return unsubscribe;
}
